### PR TITLE
face and facev can be made transparent

### PR DESCRIPTION
**Pull request by diop7**
### SUMMARY
Implements necessary changes for #[ISSUE-ID]

*Reviewers:* @numere-org/maintainers

### IMPLEMENTATION
* Implementation: (*Describe, what you've changed*) 
* Implementation test: (*Describe the type of test, which you performed, and if it was successful*)

### DOCUMENTATION
* [x] ChangesLog updated
* [x] Code changes commented
* **Documentation articles:**
    * [ ] corresponding documentation articles updated
    * [ ] new documentation articles created
    * [x] not needed
* **Language files:**
    * [ ] corresponding language files updated
    * [x] not needed

----------------

### TESTS BY REVIEWERS
* [ ] Added to the automatic SW tests
* [x] Tested manually

### CODE REVIEW

**Comment by diop7** [comment]
@numeredev does it make sense this way? a function dedicated for this would be complicated because we need to change the points for each condition (depending on the nFunctions and sCurrentDrawingFunction)

**Comment by numeredev** [comment]
> @numeredev does it make sense this way? a function dedicated for this would be complicated because we need to change the points for each condition (depending on the nFunctions and sCurrentDrawingFunction)

I think that's a misunderstanding. The idea is to provide a "drop-in" replacement for `mglGraph::Face()` via an adapter function, i.e. like so:

```C++
static void faceV2(mglGraph* _graph, const mglPoint& p1, const mglPoint& p2, const mglPoint& p3, const mglPoint& p4, const std::string& style)
{
  if (sStyle.substr(0, 1) == "#")
  {
    _graph->Line(p4, p2, sStyle.c_str());
    _graph->Line(p2, p1, sStyle.c_str());
    _graph->Line(p1, p3, sStyle.c_str());
    _graph->Line(p3, p4, sStyle.c_str());
  }
  
  _graph->Face(p1, p2, p3, p4, sStyle.c_str()); // p1-p4 might have the wrong order in this example
}
```
Now you can replace all calls to `mglGraph::Face` with this function (please ensure that `p1`- `p4` are in the correct order)

**Comment by diop7** [comment]
This code snippet can be helpful to test if the Bug is fixed
draw face(0,0, 5,0, "#")
draw face(0,0, 5,0, "@r")
draw facev(0,0, 5,0, "#")
draw facev(0,0, 5,0, "@g")

**Comment by diop7** [comment]
This could be the code to test the different possibilities
```
draw face(0,0, 5,0, "#rg"), circle(0,0,2.5,"#rg")
draw face(0,0, 5,0, "@rg"), circle(0,0,2.5,"@rg")
draw face(0,0, 5,0, "@r"), circle(0,0,2.5,"@r")
```

**Comment by numeredev** [comment]
Thanks, what you miss, is searching for all occurences of `mglGraph::Face()` and replace them with your adapter function. *Careful:* your branch was very outdated. I merged now the current main branch. Do not forget to pull first.

**Review by numeredev — APPROVED** [review]

**Pull request merged**
